[server]
# วิธีที่ 1 (แนะนำสำหรับปัญหานี้): ปิด file watcher ไปเลย
# ข้อดี: แก้ปัญหาได้แน่นอน 100%
# ข้อเสีย: หากคุณแก้ไขโค้ด ต้องกดปุ่ม Rerun หรือ Refresh ที่หน้าเว็บด้วยตนเอง
fileWatcherType = "none"

# --- หรือ ---

# วิธีที่ 2 (ทางเลือก): เปลี่ยนวิธีตรวจสอบไฟล์เป็นแบบ poll
# อาจจะยังทำงานได้ และยังคง auto-reload ได้ แต่ใช้ทรัพยากรมากกว่าเล็กน้อย
# หากต้องการลองวิธีนี้ ให้ใส่ # หน้าบรรทัด fileWatcherType = "none" แล้วเอา # หน้าบรรทัดนี้ออก
# fileWatcherType = "poll"